### ISSUE TITLE
It can't find the proccesor

### ISSUE THREAD

**Issue by bchowning** [acr8133/TUNDRA-Launch-Script#1]
[https://imgur.com/9RxLOSL](url)

**Comment by bchowning** [comment]
![KSP error](https://user-images.githubusercontent.com/3986879/120084272-6ceb8800-c094-11eb-9f84-ef14952ff540.png)

**Comment by acr8133** [comment]
Hi!
It looks like you are missing the nametags for your parts, you can refer to
the link below on which parts require changing name tags.

https://acr8133.github.io/TUNDRA-Launch-Script/

You can DM me on discord if you need further assistance: ACR#8397
,Thanks!
